name: Lighthouse CI

on: [pull_request]

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@v9
        with:
          urls: "https://matheusjardimb.com/"
          budgetPath: ".github/lighthouse/budget.json"
          uploadArtifacts: true
          temporaryPublicStorage: true
          configPath: ".github/lighthouse/lighthouserc-static-dist-dir.yml"
